# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate reqwest

Name:           rust-%{crate}
Version:        0.9.24
Release:        2%{?dist}
Summary:        Higher level HTTP client library

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/reqwest
Source:         %{crates_source}
# Initial patched metadata
# * No windows
Patch0:         reqwest-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Higher level HTTP client library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+default-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-tls-devel %{_description}

This package contains library source intended for building other packages
which use "default-tls" feature of "%{crate}" crate.

%files       -n %{name}+default-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hyper-011-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-011-devel %{_description}

This package contains library source intended for building other packages
which use "hyper-011" feature of "%{crate}" crate.

%files       -n %{name}+hyper-011-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hyper-old-types-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-old-types-devel %{_description}

This package contains library source intended for building other packages
which use "hyper-old-types" feature of "%{crate}" crate.

%files       -n %{name}+hyper-old-types-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hyper-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-rustls-devel %{_description}

This package contains library source intended for building other packages
which use "hyper-rustls" feature of "%{crate}" crate.

%files       -n %{name}+hyper-rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hyper-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-tls-devel %{_description}

This package contains library source intended for building other packages
which use "hyper-tls" feature of "%{crate}" crate.

%files       -n %{name}+hyper-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages
which use "native-tls" feature of "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages
which use "rustls" feature of "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rustls-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-devel %{_description}

This package contains library source intended for building other packages
which use "rustls-tls" feature of "%{crate}" crate.

%files       -n %{name}+rustls-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+socks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+socks-devel %{_description}

This package contains library source intended for building other packages
which use "socks" feature of "%{crate}" crate.

%files       -n %{name}+socks-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages
which use "tls" feature of "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-rustls" feature of "%{crate}" crate.

%files       -n %{name}+tokio-rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust-dns-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-resolver-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns-resolver" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-resolver-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-roots-devel %{_description}

This package contains library source intended for building other packages
which use "webpki-roots" feature of "%{crate}" crate.

%files       -n %{name}+webpki-roots-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# Skip tests requiring network and one depending on Cargo.lock being present
%cargo_test -- -- --skip test_badssl_modern --skip test_badssl_self_signed --skip test_badssl_wrong_host --skip file
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.24-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Dec 26 07:19:05 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.24-1
- Update to 0.9.24

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.13-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Jun 21 18:20:27 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.13-2
- Regenerate

* Tue Apr 02 2019 Josh Stone <jistone@redhat.com> - 0.9.13-1
- Update to 0.9.13

* Thu Mar 21 00:24:21 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.12-1
- Update to 0.9.12

* Tue Mar 05 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.11-1
- Update to 0.9.11

* Tue Feb 19 2019 Josh Stone <jistone@redhat.com> - 0.9.10-1
- Update to 0.9.10

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.9-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Jan 26 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.9-2
- Run tests in infrastructure

* Sat Jan 26 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.9-1
- Initial package
